/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_32 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] c
  );
  
  
  
  reg [16:0] result;
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h0: begin
        result = a + b;
      end
      2'h1: begin
        result = a - b;
      end
      2'h2: begin
        result = a * b;
      end
      2'h3: begin
        result = a - ((a / b) * b);
      end
      default: begin
        result = 16'h0000;
      end
    endcase
    c = result[0+15-:16];
  end
endmodule
