/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ledrow5map_43 (
    input [9:0] lane1,
    input [9:0] lane2,
    input [9:0] lane3,
    input [9:0] lane4,
    output reg [95:0] color_row5
  );
  
  
  
  reg [1:0] temp_r0;
  
  reg [1:0] temp_r1;
  
  reg [1:0] temp_r2;
  
  reg [1:0] temp_r3;
  
  reg [23:0] color_cell0;
  
  reg [23:0] color_cell1;
  
  reg [23:0] color_cell2;
  
  reg [23:0] color_cell3;
  
  always @* begin
    color_cell0 = 24'h000000;
    color_cell1 = 24'h000000;
    color_cell2 = 24'h000000;
    color_cell3 = 24'h000000;
    temp_r0 = lane1[8+1-:2];
    temp_r1 = lane2[8+1-:2];
    temp_r2 = lane3[8+1-:2];
    temp_r3 = lane4[8+1-:2];
    if (temp_r0 == 2'h0) begin
      color_cell0 = 24'h000000;
    end
    if (temp_r0 == 2'h1) begin
      color_cell0 = 24'h00ff00;
    end
    if (temp_r0 == 2'h2) begin
      color_cell0 = 24'h0000ff;
    end
    if (temp_r1 == 2'h0) begin
      color_cell1 = 24'h000000;
    end
    if (temp_r1 == 2'h1) begin
      color_cell1 = 24'h00ff00;
    end
    if (temp_r1 == 2'h2) begin
      color_cell1 = 24'h0000ff;
    end
    if (temp_r2 == 2'h0) begin
      color_cell2 = 24'h000000;
    end
    if (temp_r2 == 2'h1) begin
      color_cell2 = 24'h00ff00;
    end
    if (temp_r2 == 2'h2) begin
      color_cell2 = 24'h0000ff;
    end
    if (temp_r3 == 2'h0) begin
      color_cell3 = 24'h000000;
    end
    if (temp_r3 == 2'h1) begin
      color_cell3 = 24'h00ff00;
    end
    if (temp_r3 == 2'h2) begin
      color_cell3 = 24'h0000ff;
    end
    color_row5 = {color_cell0, color_cell1, color_cell2, color_cell3};
  end
endmodule
