/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module map_3 (
    input [4:0] address,
    input [1:0] level,
    output reg [7:0] next_row
  );
  
  
  
  localparam LEVEL1 = 176'hff820014008800180024400210002400440018000840;
  
  localparam LEVEL2 = 168'hff8801084066001188021410210840140420281042;
  
  localparam LEVEL3 = 168'hff9900662200888082082804100110401400111044;
  
  always @* begin
    
    case (level)
      2'h1: begin
        next_row = LEVEL1[(address)*8+7-:8];
      end
      2'h2: begin
        next_row = LEVEL2[(address)*8+7-:8];
      end
      2'h3: begin
        next_row = LEVEL3[(address)*8+7-:8];
      end
      default: begin
        next_row = 8'h00;
      end
    endcase
  end
endmodule
