/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip,
    input player2left,
    input player2right,
    input player1left,
    input player1right
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [4-1:0] M_car1_currentPosition;
  reg [1-1:0] M_car1_left;
  reg [1-1:0] M_car1_right;
  reg [4-1:0] M_car1_position;
  car_2 car1 (
    .clk(clk),
    .rst(rst),
    .left(M_car1_left),
    .right(M_car1_right),
    .position(M_car1_position),
    .currentPosition(M_car1_currentPosition)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = rst;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    io_led[8+7-:8] = 4'h2;
    M_car1_position = 4'h2;
    M_car1_left = io_button[0+0-:1];
    M_car1_right = io_button[1+0-:1];
    io_led[16+0+0-:1] = io_button[0+0-:1];
    io_led[16+1+0-:1] = io_button[1+0-:1];
    io_led[0+7-:8] = M_car1_currentPosition;
  end
endmodule
