/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module scoredisplay_30 (
    input [7:0] score,
    input [23:0] color,
    output reg [95:0] row1,
    output reg [95:0] row2
  );
  
  
  
  reg [23:0] temp_7;
  
  reg [23:0] temp_6;
  
  reg [23:0] temp_5;
  
  reg [23:0] temp_4;
  
  reg [23:0] temp_3;
  
  reg [23:0] temp_2;
  
  reg [23:0] temp_1;
  
  reg [23:0] temp_0;
  
  always @* begin
    if (score[7+0-:1]) begin
      temp_7 = color;
    end else begin
      temp_7 = 24'h000000;
    end
    if (score[6+0-:1]) begin
      temp_6 = color;
    end else begin
      temp_6 = 24'h000000;
    end
    if (score[5+0-:1]) begin
      temp_5 = color;
    end else begin
      temp_5 = 24'h000000;
    end
    if (score[4+0-:1]) begin
      temp_4 = color;
    end else begin
      temp_4 = 24'h000000;
    end
    if (score[3+0-:1]) begin
      temp_3 = color;
    end else begin
      temp_3 = 24'h000000;
    end
    if (score[2+0-:1]) begin
      temp_2 = color;
    end else begin
      temp_2 = 24'h000000;
    end
    if (score[1+0-:1]) begin
      temp_1 = color;
    end else begin
      temp_1 = 24'h000000;
    end
    if (score[0+0-:1]) begin
      temp_0 = color;
    end else begin
      temp_0 = 24'h000000;
    end
    row1 = {temp_4, temp_5, temp_6, temp_7};
    row2 = {temp_0, temp_1, temp_2, temp_3};
  end
endmodule
