/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 24
*/
module smallgc_2 (
    input reset,
    input clk,
    input rst,
    output reg [4:0] out
  );
  
  localparam SIZE = 5'h18;
  
  
  reg [23:0] M_counter_d, M_counter_q = 1'h0;
  
  reg [4:0] M_slow_d, M_slow_q = 1'h0;
  
  always @* begin
    M_counter_d = M_counter_q;
    M_slow_d = M_slow_q;
    
    M_counter_d = M_counter_q + 1'h1;
    out = M_slow_q;
    if (M_counter_q == 24'hffffff) begin
      M_slow_d = M_slow_q + 1'h1;
    end
    if (reset) begin
      M_counter_d = 1'h0;
      M_slow_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_slow_q <= 1'h0;
    end else begin
      M_slow_q <= M_slow_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
