/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_21 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] c
  );
  
  
  
  wire [16-1:0] M_adder_c;
  reg [6-1:0] M_adder_alufn;
  reg [16-1:0] M_adder_a;
  reg [16-1:0] M_adder_b;
  adder_32 adder (
    .alufn(M_adder_alufn),
    .a(M_adder_a),
    .b(M_adder_b),
    .c(M_adder_c)
  );
  
  wire [16-1:0] M_bitshifter_c;
  reg [6-1:0] M_bitshifter_alufn;
  reg [16-1:0] M_bitshifter_a;
  reg [16-1:0] M_bitshifter_b;
  bitshifter_33 bitshifter (
    .alufn(M_bitshifter_alufn),
    .a(M_bitshifter_a),
    .b(M_bitshifter_b),
    .c(M_bitshifter_c)
  );
  
  always @* begin
    M_adder_alufn = alufn;
    M_adder_a = a;
    M_adder_b = b;
    M_bitshifter_alufn = alufn;
    M_bitshifter_a = a;
    M_bitshifter_b = b;
    
    case (alufn[4+1-:2])
      2'h0: begin
        c = M_adder_c;
      end
      2'h2: begin
        c = M_bitshifter_c;
      end
      default: begin
        c = 16'h0000;
      end
    endcase
  end
endmodule
