/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp_37 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] c
  );
  
  
  
  reg comp;
  
  always @* begin
    
    case (alufn[1+1-:2])
      2'h1: begin
        comp = a == b;
      end
      2'h2: begin
        comp = a < b;
      end
      2'h3: begin
        comp = a <= b;
      end
      default: begin
        comp = 1'h0;
      end
    endcase
    c[0+0-:1] = comp;
    c[1+14-:15] = 15'h0000;
  end
endmodule
