/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module color_map_1 (
    input clk,
    input [9:0] lane1,
    input [9:0] lane2,
    input [9:0] lane3,
    input [9:0] lane4,
    output reg [7:0] cc1
  );
  
  
  
  reg [1:0] M_temp_r0_d, M_temp_r0_q = 1'h0;
  reg [1:0] M_temp_r1_d, M_temp_r1_q = 1'h0;
  reg [1:0] M_temp_r2_d, M_temp_r2_q = 1'h0;
  reg [1:0] M_temp_r3_d, M_temp_r3_q = 1'h0;
  reg [23:0] M_color_cell0_d, M_color_cell0_q = 1'h0;
  reg [23:0] M_color_cell1_d, M_color_cell1_q = 1'h0;
  reg [23:0] M_color_cell2_d, M_color_cell2_q = 1'h0;
  reg [23:0] M_color_cell3_d, M_color_cell3_q = 1'h0;
  
  always @* begin
    M_temp_r3_d = M_temp_r3_q;
    M_temp_r2_d = M_temp_r2_q;
    M_temp_r1_d = M_temp_r1_q;
    M_temp_r0_d = M_temp_r0_q;
    M_color_cell1_d = M_color_cell1_q;
    M_color_cell0_d = M_color_cell0_q;
    M_color_cell3_d = M_color_cell3_q;
    M_color_cell2_d = M_color_cell2_q;
    
    M_color_cell0_d = 24'h000000;
    M_color_cell1_d = 24'h000000;
    M_color_cell2_d = 24'h000000;
    M_color_cell3_d = 24'h000000;
    M_temp_r0_d = lane1[0+1-:2];
    M_temp_r1_d = lane2[0+1-:2];
    M_temp_r2_d = lane3[0+1-:2];
    M_temp_r3_d = lane4[0+1-:2];
    cc1 = 8'hff;
    if (M_temp_r0_q == 2'h0) begin
      M_color_cell0_d = 24'h000000;
      cc1 = M_color_cell0_q[0+7-:8];
    end
    if (M_temp_r0_q == 2'h1) begin
      M_color_cell0_d = 24'h010000;
      cc1 = M_color_cell0_q[0+7-:8];
    end
    if (M_temp_r0_q == 2'h2) begin
      M_color_cell0_d = 24'h000001;
      cc1 = M_color_cell0_q[0+7-:8];
    end
  end
  
  always @(posedge clk) begin
    M_temp_r0_q <= M_temp_r0_d;
    M_temp_r1_q <= M_temp_r1_d;
    M_temp_r2_q <= M_temp_r2_d;
    M_temp_r3_q <= M_temp_r3_d;
    M_color_cell0_q <= M_color_cell0_d;
    M_color_cell1_q <= M_color_cell1_d;
    M_color_cell2_q <= M_color_cell2_d;
    M_color_cell3_q <= M_color_cell3_d;
  end
  
endmodule
