/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ledrowcars_29 (
    input [3:0] car1,
    input [3:0] car2,
    output reg [95:0] colorrowcar
  );
  
  
  
  reg [23:0] color_cell0;
  
  reg [23:0] color_cell1;
  
  reg [23:0] color_cell2;
  
  reg [23:0] color_cell3;
  
  always @* begin
    color_cell0 = 24'h000000;
    color_cell1 = 24'h000000;
    color_cell2 = 24'h000000;
    color_cell3 = 24'h000000;
    if (car1 == 4'h3) begin
      color_cell0 = 24'hffffff;
      color_cell1 = 24'h000000;
    end
    if (car1 == 4'hc) begin
      color_cell0 = 24'h000000;
      color_cell1 = 24'hffffff;
    end
    if (car2 == 4'h3) begin
      color_cell2 = 24'h00ffff;
      color_cell3 = 24'h000000;
    end
    if (car2 == 4'hc) begin
      color_cell2 = 24'h000000;
      color_cell3 = 24'h00ffff;
    end
    colorrowcar = {color_cell0, color_cell1, color_cell2, color_cell3};
  end
endmodule
