/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module smallgc_2 (
    input reset,
    input clk,
    input rst,
    output reg [4:0] out
  );
  
  
  
  reg [24:0] M_counter_d, M_counter_q = 1'h0;
  
  wire [5-1:0] M_ctr_out;
  reg [1-1:0] M_ctr_clk;
  reg [1-1:0] M_ctr_rst_sig;
  mariocounter_4 ctr (
    .rst(rst),
    .clk(M_ctr_clk),
    .rst_sig(M_ctr_rst_sig),
    .out(M_ctr_out)
  );
  
  always @* begin
    M_counter_d = M_counter_q;
    
    M_ctr_clk = M_counter_q[24+0-:1];
    M_ctr_rst_sig = reset;
    M_counter_d = M_counter_q + 1'h1;
    out = M_ctr_out;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
    end
  end
  
endmodule
